apiVersion: batch/v1
kind: Job
metadata:
  name: ping-job-fail
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: ping-container
          image: busybox:latest
          imagePullPolicy: Always
          command: ["ping", "baddomain", "-c", "1"]
      restartPolicy: Never
  backoffLimit: 4
