apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config-v2
data:
  COOL_FACTOR: "5000"
  USE_LEFT_HANDED_DOORKNOBS: "True"
  "elevator.config": |
    all-floors: no
    express: only on wendnedays
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-config-deployment
  labels:
    app: example-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-config
  template:
    metadata:
      name: example-config
      labels:
        app: example-config
    spec:
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: example-config-v2
      containers:
        - name: main-container
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: busybox
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: COOL_FACTOR
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: example-config-v2
                  # Specify the key associated with the value
                  key: COOL_FACTOR
            - name: DOORKNOBS_ARE_LEFT_HANDED
              valueFrom:
                configMapKeyRef:
                  name: example-config-v2
                  key: USE_LEFT_HANDED_DOORKNOBS
          args:
            - /bin/sh
            - -c
            - >
              while true; do
                echo "$(date) INFO hello from main-container";
                sleep 1;
              done
