apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-30T17:46:38Z"
  name: example-config-pod
  namespace: default
  resourceVersion: "31220"
  uid: c1992068-ab3a-4998-b0f8-1126ed8b951e
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date) INFO hello from main-container";
            sleep 1;
          done
      image: busybox
      imagePullPolicy: Always
      name: main-container
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-sl776
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-sl776
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-11-30T17:46:38Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-11-30T17:46:41Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-11-30T17:46:41Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-11-30T17:46:38Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://dcad0ede8ca07b4bc88df8d2c07e1096c267cebefeecf40a1c91ebdf8048252a
      image: busybox:latest
      imageID: docker-pullable://busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
      lastState: {}
      name: main-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-11-30T17:46:40Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.89
  podIPs:
    - ip: 10.1.0.89
  qosClass: BestEffort
  startTime: "2023-11-30T17:46:38Z"
