apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv3
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /tmp/demo-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-smaller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5G
  storageClassName: standard
  volumeName: demo-pv3
