apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-12-01T16:27:39Z"
  generateName: frontend-c6ff96854-
  labels:
    app: guestbook
    pod-template-hash: c6ff96854
    tier: frontend
  name: frontend-c6ff96854-j8v58
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: frontend-c6ff96854
      uid: aa1de20e-0107-4788-9e8c-3a93f65de62a
  resourceVersion: "73717"
  uid: 0da28b24-6585-4181-bbac-85b13f8419d5
spec:
  containers:
    - env:
        - name: GET_HOSTS_FROM
          value: dns
      image: gcr.io/google_samples/gb-frontend:v5
      imagePullPolicy: IfNotPresent
      name: php-redis
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-wmjms
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-wmjms
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-12-01T16:27:39Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-12-01T16:27:39Z"
      message: "containers with unready status: [php-redis]"
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-12-01T16:27:39Z"
      message: "containers with unready status: [php-redis]"
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-12-01T16:27:39Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - image: gcr.io/google_samples/gb-frontend:v5
      imageID: ""
      lastState: {}
      name: php-redis
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: Back-off pulling image "gcr.io/google_samples/gb-frontend:v5"
          reason: ImagePullBackOff
  hostIP: 192.168.65.3
  phase: Pending
  podIP: 10.1.0.116
  podIPs:
    - ip: 10.1.0.116
  qosClass: Burstable
  startTime: "2023-12-01T16:27:39Z"
